### PR TITLE
Converted links to substitutions, fixed tables

### PR DESCRIPTION
**Pull request by veermetri05**
Created labels for all sections on all pages. Converted old links to substitutions, due to conversion of old links to substitutions the tables were not formatted, have fixed it.

### CODE REVIEW

**Comment by ice0** [comment]
@veermetri05 
Hi! Any issues with this PR? I wanted to check it today, but it is already closed.

**Comment by morevnaproject** [comment]
Re-opening for now...

**Comment by veermetri05** [comment]
I have fixed most (atleast all) the links that didn't work after migrating from old wiki to new docs. I have created necessary empty pages wherever pages didn't exist. Hopefully most of the links are working
Please merge this

**Comment by veermetri05** [comment]
For reference:
https://forums.synfig.org/t/documentation-contribution/12186?u=veermetri05

**Pull request merged**
